vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /media/product
            upload_destination: '%kernel.project_dir%/public/media/product'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
